version: '3'

services:
  nazcaxapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: nazca-docker
    container_name: nazcaxapp
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}     # en .env => db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}

  db:
    image: postgres:14.3
    restart: always
    container_name: nazcadb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}   # opcional pero recomendable
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres-db:
    external: false